[project]
name = "invoicelayoutandprinting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easyofd>=0.5.6",
    "nuitka>=2.8.6",
    "ofdparser>=0.0.8",
    "pypdf>=3.9",
    "pyqt6>=6.5",
]
